[project]
name = "agentdevelopmentkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.5.5",
    "fastapi>=0.115.12",
    "google-adk>=0.4.0",
    "litellm>=1.70.0",
    "uvicorn>=0.34.2",
]
